# ==================================================
# Default development settings
# ==================================================

spring.application.name=lifegame

# Show useful error information while developing.
server.error.include-message=always
server.error.include-stacktrace=on_param
server.error.include-binding-errors=always

# Development log level.
logging.level.root=INFO
logging.level.com.mkunori.lifegame=DEBUG